---
Description: Root Stack for AWS Amplify CLI
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DeploymentBucketName:
    Type: String
    Default: DeploymentBucket
    Description: Name of the common deployment bucket provided by the parent stack
  AuthRoleName:
    Type: String
    Default: AuthRoleName
    Description: Name of the common deployment bucket provided by the parent stack
  UnauthRoleName:
    Type: String
    Default: UnAuthRoleName
    Description: Name of the common deployment bucket provided by the parent stack
Outputs:
  Region:
    Description: CloudFormation provider root stack Region
    Value:
      Ref: AWS::Region
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-Region"
  StackName:
    Description: CloudFormation provider root stack ID
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-StackName"
  StackId:
    Description: CloudFormation provider root stack name
    Value:
      Ref: AWS::StackId
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-StackId"
  AuthRoleArn:
    Value:
      Fn::GetAtt:
        - AuthRole
        - Arn
  UnauthRoleArn:
    Value:
      Fn::GetAtt:
        - UnauthRole
        - Arn
  DeploymentBucketName:
    Description: CloudFormation provider root stack deployment bucket name
    Value:
      Ref: DeploymentBucketName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DeploymentBucketName"
  AuthRoleName:
    Value:
      Ref: AuthRole
  UnauthRoleName:
    Value:
      Ref: UnauthRole
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: DeploymentBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  AuthRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
      RoleName:
        Ref: AuthRoleName
  UnauthRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
      RoleName:
        Ref: UnauthRoleName
  functionfunnuevoinmueble:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-viviendaapp-dev-115016-deployment/amplify-cfn-templates/function/funnuevoinmueble-cloudformation-template.json
      Parameters:
        deploymentBucketName: amplify-viviendaapp-dev-115016-deployment
        s3Key: amplify-builds/funnuevoinmueble-72436636417450667873-build.zip
        functionfunviviendaserviceName:
          Fn::GetAtt:
            - functionfunviviendaservice
            - Outputs.Name
        env: dev
  functionfunobtenerinmueble:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-viviendaapp-dev-115016-deployment/amplify-cfn-templates/function/funobtenerinmueble-cloudformation-template.json
      Parameters:
        deploymentBucketName: amplify-viviendaapp-dev-115016-deployment
        s3Key: amplify-builds/funobtenerinmueble-544c7753524739424b57-build.zip
        functionfunviviendaserviceName:
          Fn::GetAtt:
            - functionfunviviendaservice
            - Outputs.Name
        env: dev
  functionfunobtenerinmuebles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-viviendaapp-dev-115016-deployment/amplify-cfn-templates/function/funobtenerinmuebles-cloudformation-template.json
      Parameters:
        deploymentBucketName: amplify-viviendaapp-dev-115016-deployment
        s3Key: amplify-builds/funobtenerinmuebles-35544752364273746c34-build.zip
        functionfunviviendaserviceName:
          Fn::GetAtt:
            - functionfunviviendaservice
            - Outputs.Name
        env: dev
  functionfunborrarinmueble:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-viviendaapp-dev-115016-deployment/amplify-cfn-templates/function/funborrarinmueble-cloudformation-template.json
      Parameters:
        deploymentBucketName: amplify-viviendaapp-dev-115016-deployment
        s3Key: amplify-builds/funborrarinmueble-5364566c535274337158-build.zip
        functionfunviviendaserviceName:
          Fn::GetAtt:
            - functionfunviviendaservice
            - Outputs.Name
        env: dev
  functionfunobtenerpropietario:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-viviendaapp-dev-115016-deployment/amplify-cfn-templates/function/funobtenerpropietario-cloudformation-template.json
      Parameters:
        deploymentBucketName: amplify-viviendaapp-dev-115016-deployment
        s3Key: amplify-builds/funobtenerpropietario-59304c314a334f796239-build.zip
        functionfunviviendaserviceName:
          Fn::GetAtt:
            - functionfunviviendaservice
            - Outputs.Name
        env: dev
  functionfunviviendaservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-viviendaapp-dev-115016-deployment/amplify-cfn-templates/function/funviviendaservice-cloudformation-template.json
      Parameters:
        secretsPathAmplifyAppId: d4iiuw3h9e10g
        deploymentBucketName: amplify-viviendaapp-dev-115016-deployment
        s3Key: amplify-builds/funviviendaservice-7849564f61796b637368-build.zip
        env: dev
  functionfunstartdb:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-viviendaapp-dev-115016-deployment/amplify-cfn-templates/function/funstartdb-cloudformation-template.json
      Parameters:
        cleanDb: 'TRUE'
        deploymentBucketName: amplify-viviendaapp-dev-115016-deployment
        s3Key: amplify-builds/funstartdb-4d6f75436a6b46674d5a-build.zip
        functionfunviviendaserviceName:
          Fn::GetAtt:
            - functionfunviviendaservice
            - Outputs.Name
        env: dev
  apiapivivienda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/amplify-viviendaapp-dev-115016-deployment/amplify-cfn-templates/api/apivivienda-cloudformation-template.json
      Parameters:
        functionfunnuevoinmuebleName:
          Fn::GetAtt:
            - functionfunnuevoinmueble
            - Outputs.Name
        functionfunnuevoinmuebleArn:
          Fn::GetAtt:
            - functionfunnuevoinmueble
            - Outputs.Arn
        functionfunobtenerinmuebleName:
          Fn::GetAtt:
            - functionfunobtenerinmueble
            - Outputs.Name
        functionfunobtenerinmuebleArn:
          Fn::GetAtt:
            - functionfunobtenerinmueble
            - Outputs.Arn
        functionfunobtenerinmueblesName:
          Fn::GetAtt:
            - functionfunobtenerinmuebles
            - Outputs.Name
        functionfunobtenerinmueblesArn:
          Fn::GetAtt:
            - functionfunobtenerinmuebles
            - Outputs.Arn
        functionfunborrarinmuebleName:
          Fn::GetAtt:
            - functionfunborrarinmueble
            - Outputs.Name
        functionfunborrarinmuebleArn:
          Fn::GetAtt:
            - functionfunborrarinmueble
            - Outputs.Arn
        functionfunobtenerpropietarioName:
          Fn::GetAtt:
            - functionfunobtenerpropietario
            - Outputs.Name
        functionfunobtenerpropietarioArn:
          Fn::GetAtt:
            - functionfunobtenerpropietario
            - Outputs.Arn
        functionfunstartdbName:
          Fn::GetAtt:
            - functionfunstartdb
            - Outputs.Name
        functionfunstartdbArn:
          Fn::GetAtt:
            - functionfunstartdb
            - Outputs.Arn
        env: dev
